### ISSUE TITLE
The local results are poor

### ISSUE THREAD

**Issue by whw2021** [ChenHongruixuan/SRGCAE#7]
The following are the results I obtained after executing the file train_SRGCAE_Local.py.
![SRGCAE_EdgeConc_DI](https://github.com/user-attachments/assets/8157b1f1-85bc-42cb-8f8d-f2c4a9c03d22)
![SRGCAE_EdgeConc_1725586470 5939867](https://github.com/user-attachments/assets/88bafcf6-8933-440e-b210-02414ccb826b)

I didn't adjust the parameters; why is the performance so poor?

**Comment by ChenHongruixuan** [comment]
Hi @whw2021 ,

Thank you for your question. I tried our upload code. Please enlarge the epoch to 45 and this problem should be solved.

Best,

**Comment by PradeepYLN** [comment]
@ChenHongruixuan I am trying it on new sample. Could you please help me on how to fix the below error?
```
Traceback (most recent call last):
  File "/SRGCAE/train_SRGCAE_Local.py", line 151, in <module>
    train_model(args)
  File "/SRGCAE/train_SRGCAE_Local.py", line 74, in train_model
    feat_t1 = GCAE_model(node_t1, norm_adj_t1)
  File "/app/indices/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/app/indices/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/SRGCAE/model/SRGCAE.py", line 35, in forward
    x = torch.sigmoid(self.gc1(x, adj))
  File "/app/indices/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/app/indices/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "SRGCAE/model/GraphConv.py", line 32, in forward
    support = torch.mm(x, self.weight)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (361x4 and 3x16)
```

**Comment by whw2021** [comment]
> Hi @whw2021 ,
> 
> Thank you for your question. I tried our upload code. Please enlarge the epoch to 45 and this problem should be solved.
> 
> Best,

Thank you for your response. Following your advice, I indeed achieved good results on the shuguang dataset, but the performance on other datasets is still very poor. For example, the following figure shows the local and nonlocal results I obtained on Gloucester, which are far from what is presented in your paper. I would like to understand why this is the case and hope to receive your explanation.
![Gloucester1_EdgeConc_45](https://github.com/user-attachments/assets/d3b67f51-c2fe-45a9-ad8a-d95427f7df3c)
![Gloucester1_Nonlocal_45](https://github.com/user-attachments/assets/a490b60d-73e2-4c5e-9016-024180c0976f)
